"""Send prep pack emails via Gmail (OAuth) or SMTP fallback."""
import hashlib
import json
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from sqlalchemy.orm import Session

from backend.config import get_settings
from backend.models import EmailDeliveryLog, PrepPack, CalendarEvent, EventClassification, User, OAuthToken, SyncLog
from backend.services import ggmail

settings = get_settings()


def _compute_email_hash(to: str, subject: str, body: str) -> str:
    content = f"{to}||{subject}||{body}"
    return hashlib.sha256(content.encode()).hexdigest()


def _render_html(pack: PrepPack, event: CalendarEvent, classification: Optional[EventClassification]) -> str:
    talking_points = json.loads(pack.talking_points or "[]")
    expected_questions = json.loads(pack.expected_questions or "[]")
    questions_to_ask = json.loads(pack.questions_to_ask or "[]")
    checklist = json.loads(pack.prep_checklist or "[]")
    caveats = json.loads(pack.caveats or "[]")

    company = (classification.company_name if classification else None) or "the company"
    role = (classification.role_title if classification else None) or "the role"
    meeting_type = (classification.effective_label if classification else "meeting").replace("_", " ").title()
    date_str = event.start_time.strftime("%A, %B %d at %I:%M %p UTC")

    def ul(items: list) -> str:
        return "<ul>" + "".join(f"<li>{i}</li>" for i in items) + "</ul>"

    def qa_list(items: list) -> str:
        parts = []
        for item in items:
            if isinstance(item, dict):
                parts.append(
                    f"<li><strong>Q: {item.get('question', '')}</strong><br>"
                    f"<em>Suggested approach:</em> {item.get('suggested_answer', '')}</li>"
                )
            else:
                parts.append(f"<li>{item}</li>")
        return "<ul>" + "".join(parts) + "</ul>"

    checklist_html = "<ul>" + "".join(
        f"<li>☐ {(i['item'] if isinstance(i, dict) else i)}</li>" for i in checklist
    ) + "</ul>"

    caveat_section = ""
    if caveats:
        caveat_section = f"""
        <div style="background:#fff8e1;border-left:4px solid #ffc107;padding:12px;margin:16px 0">
          <strong>Caveats & Assumptions</strong>
          {ul(caveats)}
        </div>"""

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 700px; margin: 0 auto; padding: 20px; }}
  h1 {{ color: #1a56db; font-size: 22px; }}
  h2 {{ color: #374151; font-size: 16px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-top: 24px; }}
  .meta {{ background: #f3f4f6; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px; }}
  .meta p {{ margin: 4px 0; }}
  ul {{ padding-left: 20px; line-height: 1.8; }}
  li {{ margin-bottom: 4px; }}
  .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 13px; }}
</style></head>
<body>
  <h1>Meeting Prep: {event.title}</h1>
  <div class="meta">
    <p><strong>Meeting type:</strong> {meeting_type}</p>
    <p><strong>Company:</strong> {company}</p>
    <p><strong>Role:</strong> {role}</p>
    <p><strong>When:</strong> {date_str}</p>
  </div>

  <h2>Meeting Summary</h2>
  <p>{pack.meeting_summary or 'No summary generated.'}</p>

  <h2>Talking Points</h2>
  {ul(talking_points) if talking_points else '<p>None generated.</p>'}

  <h2>Questions You May Be Asked</h2>
  {qa_list(expected_questions) if expected_questions else '<p>None generated.</p>'}

  <h2>Questions to Ask Them</h2>
  {ul(questions_to_ask) if questions_to_ask else '<p>None generated.</p>'}

  <h2>30-Minute Prep Checklist</h2>
  {checklist_html if checklist else '<p>None generated.</p>'}

  {caveat_section}

  <div class="footer">
    Generated by Job Prep Agent · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
  </div>
</body>
</html>
"""


def _render_plain(pack: PrepPack, event: CalendarEvent) -> str:
    """Simple plain-text fallback."""
    lines = [
        f"MEETING PREP: {event.title}",
        f"When: {event.start_time.strftime('%A, %B %d at %I:%M %p UTC')}",
        "",
        "SUMMARY",
        pack.meeting_summary or "(none)",
        "",
        "TALKING POINTS",
    ]
    for tp in json.loads(pack.talking_points or "[]"):
        lines.append(f"  • {tp}")
    lines += ["", "PREP CHECKLIST"]
    for item in json.loads(pack.prep_checklist or "[]"):
        label = item["item"] if isinstance(item, dict) else item
        lines.append(f"  ☐ {label}")
    return "\n".join(lines)


def _send_via_smtp(to: str, subject: str, html_body: str, plain_body: str) -> str:
    """Send via SMTP (Gmail App Password). Returns a pseudo message-id."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.smtp_user
    msg["To"] = to
    msg.attach(MIMEText(plain_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))
    with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as s:
        s.ehlo()
        s.starttls()
        s.login(settings.smtp_user, settings.smtp_pass)
        s.sendmail(settings.smtp_user, [to], msg.as_string())
    return f"smtp-{datetime.utcnow().timestamp()}"


def send_prep_pack_email(
    prep_pack_id: int,
    user_id: int,
    db: Session,
    recipient_email: Optional[str] = None,
) -> dict:
    """Send the prep pack email. Skips if a duplicate is detected.

    recipient_email overrides the user's stored email for this send only — it is
    never persisted. Used for tester/demo email overrides.

    Returns a dict with status and message_id.
    """
    pack = db.query(PrepPack).filter(PrepPack.id == prep_pack_id).first()
    if not pack:
        raise ValueError(f"PrepPack {prep_pack_id} not found")
    if pack.generation_status != "done":
        raise ValueError(f"PrepPack {prep_pack_id} is not ready (status: {pack.generation_status})")

    user = db.query(User).filter(User.id == user_id).first()
    event = db.query(CalendarEvent).filter(CalendarEvent.id == pack.event_id).first()
    classification = (
        db.query(EventClassification).filter(EventClassification.event_id == pack.event_id).first()
    )

    company = (classification.company_name if classification else None) or event.title
    meeting_type = (classification.effective_label if classification else "meeting").replace("_", " ").title()
    date_str = event.start_time.strftime("%b %d")

    subject = f"Prep Pack: {meeting_type} with {company} on {date_str}"
    html_body = _render_html(pack, event, classification)
    plain_body = _render_plain(pack, event)
    recipient = recipient_email or user.email

    content_hash = _compute_email_hash(recipient, subject, html_body)

    # Layer 3 dedup: check if this exact email was already sent
    existing_log = (
        db.query(EmailDeliveryLog)
        .filter(EmailDeliveryLog.content_hash == content_hash)
        .first()
    )
    if existing_log and existing_log.status == "sent":
        log = EmailDeliveryLog(
            user_id=user_id,
            prep_pack_id=prep_pack_id,
            recipient_email=recipient,
            subject=subject,
            content_hash=content_hash + f"_dup_{datetime.utcnow().timestamp()}",
            status="skipped_duplicate",
        )
        db.add(log)
        db.commit()
        _log(db, user_id, "email", "success", f"Skipped duplicate email for prep pack {prep_pack_id}")
        return {"status": "skipped_duplicate", "message_id": None}

    # Send the email — Gmail OAuth if connected, else SMTP fallback
    has_oauth = db.query(OAuthToken).filter(
        OAuthToken.user_id == user_id,
        OAuthToken.provider == "google",
    ).first() is not None

    message_id = None
    try:
        if has_oauth:
            message_id = ggmail.send_email(
                user_id=user_id, db=db, to=recipient,
                subject=subject, html_body=html_body, plain_body=plain_body,
            )
        elif settings.smtp_user and settings.smtp_pass:
            message_id = _send_via_smtp(recipient, subject, html_body, plain_body)
        else:
            raise RuntimeError(
                "No email transport available: user has no Google OAuth and SMTP is not configured."
            )
    except Exception as e:
        if message_id is None:  # Email was never sent — log and surface the error
            try:
                db.add(EmailDeliveryLog(
                    user_id=user_id, prep_pack_id=prep_pack_id,
                    recipient_email=recipient, subject=subject,
                    content_hash=content_hash + f"_fail_{datetime.utcnow().timestamp()}",
                    status="failed", error_message=str(e),
                ))
                db.commit()
            except Exception:
                pass
            raise

    # Email was sent — log best-effort, never let a DB hiccup surface as a UI error
    try:
        db.add(EmailDeliveryLog(
            user_id=user_id, prep_pack_id=prep_pack_id,
            recipient_email=recipient, subject=subject,
            content_hash=content_hash, gmail_message_id=message_id,
            status="sent", sent_at=datetime.utcnow(),
        ))
        db.commit()
        _log(db, user_id, "email", "success", f"Sent prep pack email for event '{event.title}' to {recipient}")
    except Exception:
        pass

    return {"status": "sent", "message_id": message_id}


def _log(db: Session, user_id: int, sync_type: str, status: str, details: str):
    entry = SyncLog(
        user_id=user_id,
        sync_type=sync_type,
        status=status,
        details=details[:2000],
    )
    db.add(entry)
    db.commit()
